import {
  ConflictException,
  Injectable,
  NotFoundException,
} from '@nestjs/common';
import { CreateOrganizationDto } from './dto/create-organization.dto';
import { UpdateOrganizationDto } from './dto/update-organization.dto';
import { PrismaService } from 'src/prisma/prisma';
import { errorResponse } from 'src/utils/response';
import { uniqueSlug } from 'src/common/slug.util';
import { SeoService } from 'src/seo/seo.service';
import { SeoEntity } from '@prisma/client';

@Injectable()
export class OrganizationService {
  constructor(
    private readonly prisma: PrismaService,
    private readonly seoService: SeoService,
  ) {}

  async create(createOrganizationDto: CreateOrganizationDto) {
    try {
      const { name, categoryId, inn, seo } = createOrganizationDto;

      const exists = await this.prisma.organization.findFirst({
        where: { OR: [{ name }, { inn }] },
      });
      if (exists) {
        throw new ConflictException(
          'Organization with this name or inn already exists',
        );
      }

      const category = await this.prisma.category.findUnique({
        where: { id: categoryId },
        include: { parent: true },
      });
      if (!category) {
        throw new NotFoundException('Category not found');
      }

      const slug = await uniqueSlug(name, async (candidate) => {
        const found = await this.prisma.organization.findUnique({
          where: { slug: candidate },
          select: { id: true },
        });
        return !!found;
      });

      const newOrganization = await this.prisma.$transaction(async (tx) => {
        const { seo: _, ...orgData } = createOrganizationDto;

        const organization = await tx.organization.create({
          data: {
            ...orgData,
            slug,
          },
        });

        if (seo) {
          await this.seoService.upsertSeo(SeoEntity.ORGANIZATION, organization.id, {
            ...seo,
            autoGenerated: false,
          });
        } else {
          const primaryBranch = await tx.branch.findFirst({
            where: { organizationId: organization.id },
            include: { district: { include: { region: true } } },
          });

          const city = primaryBranch?.district?.region?.nameUz;
          const categoryName = category.nameUz;

          const generatedSeo = this.seoService.generateOrganizationSeo({
            name,
            category: categoryName,
            city,
            slug,
          });

          await this.seoService.upsertSeo(SeoEntity.ORGANIZATION, organization.id, generatedSeo);
        }

        return organization;
      });

      return newOrganization;
    } catch (error) {
      errorResponse(error);
    }
  }

  async findOne(id: string) {
    try {
      const organization = await this.prisma.organization.findUnique({
        where: { id },
        include: {
          users: true,
          branches: true,
          category: true,
        },
      });

      if (!organization) {
        throw new NotFoundException('Organization not found');
      }

      const seo = await this.seoService.findSeo(SeoEntity.ORGANIZATION, id);

      return {
        ...organization,
        seo,
      };
    } catch (error) {
      errorResponse(error);
    }
  }

  async findByNameINN(name?: string, inn?: number) {
    try {
      if (name === undefined && inn === undefined) {
        const organizations = await this.prisma.organization.findMany({
          include: { users: true, branches: true, category: true },
        });

        const orgIds = organizations.map((org) => org.id);
        const seoRecords = await this.prisma.seo.findMany({
          where: {
            entityType: SeoEntity.ORGANIZATION,
            entityId: { in: orgIds },
          },
        });

        const seoMap = new Map(seoRecords.map((seo) => [seo.entityId, seo]));

        return organizations.map((org) => ({
          ...org,
          seo: seoMap.get(org.id),
        }));
      }

      const filters: any[] = [];

      if (name) {
        filters.push({ name: { contains: name, mode: 'insensitive' } });
      }
      if (inn !== undefined && inn !== null) {
        filters.push({ inn });
      }
      if (filters.length === 0) {
        return await this.prisma.organization.findMany();
      }

      const organizations = await this.prisma.organization.findMany({
        where: { OR: filters },
        include: { users: true, branches: true, category: true },
      });

      const orgIds = organizations.map((org) => org.id);
      const seoRecords = await this.prisma.seo.findMany({
        where: {
          entityType: SeoEntity.ORGANIZATION,
          entityId: { in: orgIds },
        },
      });

      const seoMap = new Map(seoRecords.map((seo) => [seo.entityId, seo]));

      return organizations.map((org) => ({
        ...org,
        seo: seoMap.get(org.id),
      }));
    } catch (error) {
      errorResponse(error);
    }
  }

  async update(id: string, updateOrganizationDto: UpdateOrganizationDto) {
    try {
      const org = await this.prisma.organization.findUnique({
        where: { id },
        include: { category: true },
      });

      if (!org) {
        throw new NotFoundException('Organization not found');
      }

      const { seo, ...orgData } = updateOrganizationDto;

      await this.prisma.$transaction(async (tx) => {
        await tx.organization.update({
          where: { id },
          data: {
            ...orgData,
            inn: org.inn,
            categoryId: org.categoryId,
          },
        });

        if (seo) {
          await this.seoService.upsertSeo(SeoEntity.ORGANIZATION, id, {
            ...seo,
            autoGenerated: false,
          });
        }
      });

      return this.findOne(id);
    } catch (error) {
      errorResponse(error);
    }
  }

  async remove(id: string) {
    try {
      await this.seoService.deleteSeo(SeoEntity.ORGANIZATION, id);

      return await this.prisma.organization.delete({
        where: { id },
      });
    } catch (error) {
      errorResponse(error);
    }
  }
}
