import {
  ConflictException,
  Injectable,
  NotFoundException,
} from '@nestjs/common';
import { CreateCategoryDto } from './dto/create-category.dto';
import { UpdateCategoryDto } from './dto/update-category.dto';
import { PrismaService } from 'src/prisma/prisma';
import { errorResponse } from 'src/utils/response';
import { translateText } from 'src/utils/translate';
import { SeoService } from 'src/seo/seo.service';
import { SeoEntity } from '@prisma/client';

@Injectable()
export class CategoryService {
  constructor(
    private readonly prisma: PrismaService,
    private readonly seoService: SeoService,
  ) { }

  async create(createCategoryDto: CreateCategoryDto) {
    try {
      const { nameUz, descriptionUz, shortDescriptionUz, seo, slug, parentId } = createCategoryDto;

      const existsCategory = await this.prisma.category.findFirst({
        where: { nameUz },
      });

      const [
        nameRu,
        nameEn,
        descriptionRu,
        descriptionEn,
        shortDescriptionRu,
        shortDescriptionEn,
      ] = await Promise.all([
        nameUz ? translateText(nameUz, "ru") : Promise.resolve(undefined),
        nameUz ? translateText(nameUz, "en") : Promise.resolve(undefined),

        descriptionUz
          ? translateText(descriptionUz, "ru")
          : Promise.resolve(undefined),

        descriptionUz
          ? translateText(descriptionUz, "en")
          : Promise.resolve(undefined),

        shortDescriptionUz
          ? translateText(shortDescriptionUz, "ru")
          : Promise.resolve(undefined),

        shortDescriptionUz
          ? translateText(shortDescriptionUz, "en")
          : Promise.resolve(undefined),
      ]);
      if (existsCategory) {
        throw new ConflictException('Category already exists');
      }

      const finalParentId = parentId === '' ? undefined : parentId;

      const category = await this.prisma.$transaction(async (tx) => {
        const data: any = {
          ...createCategoryDto,
          parentId: finalParentId,
          seo: undefined,
        };

        if (nameRu) data.nameRu = nameRu;
        if (nameEn) data.nameEn = nameEn;
        if (descriptionRu) data.descriptionRu = descriptionRu;
        if (descriptionEn) data.descriptionEn = descriptionEn;
        if (shortDescriptionRu) data.shortDescriptionRu = shortDescriptionRu;
        if (shortDescriptionEn) data.shortDescriptionEn = shortDescriptionEn;

        const newCategory = await tx.category.create({
          data,
        });

        let parentName: string | undefined;
        if (finalParentId) {
          const parent = await tx.category.findUnique({
            where: { id: finalParentId },
            select: { nameUz: true },
          });
          parentName = parent?.nameUz;
        }

        if (seo) {
          await this.seoService.upsertSeo(SeoEntity.CATEGORY, newCategory.id, {
            ...seo,
            autoGenerated: false,
          });
        } else {
          const generatedSeo = this.seoService.generateCategorySeo({
            name: nameUz,
            slug,
            parentName,
          });

          await this.seoService.upsertSeo(SeoEntity.CATEGORY, newCategory.id, generatedSeo);
        }

        return newCategory;
      });

      return category;
    } catch (error) {
      errorResponse(error);
    }
  }

  async findAll() {
    try {
      const categories = await this.prisma.category.findMany({
        orderBy: { createdAt: 'desc' },
      });

      const categoryIds = categories.map((cat) => cat.id);
      const seoRecords = await this.prisma.seo.findMany({
        where: {
          entityType: SeoEntity.CATEGORY,
          entityId: { in: categoryIds },
        },
      });

      const seoMap = new Map(seoRecords.map((seo) => [seo.entityId, seo]));

      return categories.map((cat) => ({
        ...cat,
        seo: seoMap.get(cat.id),
      }));
    } catch (error) {
      errorResponse(error);
    }
  }

  async findOne(id: string) {
    try {
      const category = await this.prisma.category.findFirst({
        where: { id },
      });

      if (!category) {
        throw new NotFoundException('Category not found');
      }

      const seo = await this.seoService.findSeo(SeoEntity.CATEGORY, id);

      return {
        ...category,
        seo,
      };
    } catch (error) {
      errorResponse(error);
    }
  }

  async findParent(parentId: string) {
    try {
      const parentCategory = await this.prisma.category.findMany({
        where: { parentId },
      });

      if (!parentCategory || parentCategory.length === 0) {
        throw new NotFoundException('Parent category not found');
      }

      const categoryIds = parentCategory.map((cat) => cat.id);
      const seoRecords = await this.prisma.seo.findMany({
        where: {
          entityType: SeoEntity.CATEGORY,
          entityId: { in: categoryIds },
        },
      });

      const seoMap = new Map(seoRecords.map((seo) => [seo.entityId, seo]));

      return parentCategory.map((cat) => ({
        ...cat,
        seo: seoMap.get(cat.id),
      }));
    } catch (error) {
      errorResponse(error);
    }
  }

  async update(id: string, updateCategoryDto: UpdateCategoryDto) {
    try {
      await this.findOne(id);

      const { seo, ...categoryData } = updateCategoryDto;

      await this.prisma.$transaction(async (tx) => {
        await tx.category.update({
          where: { id },
          data: categoryData,
        });

        if (seo) {
          await this.seoService.upsertSeo(SeoEntity.CATEGORY, id, {
            ...seo,
            autoGenerated: false,
          });
        }
      });

      return this.findOne(id);
    } catch (error) {
      errorResponse(error);
    }
  }

  async remove(id: string) {
    try {
      await this.seoService.deleteSeo(SeoEntity.CATEGORY, id);

      const delCategory = await this.prisma.category.delete({
        where: { id },
      });
      return delCategory;
    } catch (error) {
      console.log(error);
      errorResponse(error);
    }
  }
}
