import { ConflictException, Injectable, NotFoundException } from '@nestjs/common';
import { CreateServiceDto } from './dto/create-service.dto';
import { UpdateServiceDto } from './dto/update-service.dto';
import { PrismaService } from 'src/prisma/prisma';
import { CategoryService } from 'src/category/category.service';
import { translateText } from 'src/utils/translate';
import { errorResponse } from 'src/utils/response';
import { SeoService } from 'src/seo/seo.service';
import { SeoEntity } from '@prisma/client';

@Injectable()
export class ServiceService {
  constructor(
    private readonly prisma: PrismaService,
    private readonly categoryService: CategoryService,
    private readonly seoService: SeoService,
  ) {}

  async create(createServiceDto: CreateServiceDto) {
    try {
      const { categoryId, nameUz, descriptionUz, seo, slug } = createServiceDto;

      const category = await this.categoryService.findOne(categoryId);
      if (!category) {
        throw new NotFoundException('Category not found');
      }

      const service = await this.prisma.service.findFirst({ where: { nameUz } });
      if (service) {
        throw new ConflictException('Service already exists');
      }

      const nameRu = nameUz ? await translateText(nameUz, 'ru') : undefined;
      const nameEn = nameUz ? await translateText(nameUz, 'en') : undefined;

      const description = descriptionUz || '';
      const descriptionEn = description ? await translateText(description, 'en') : undefined;
      const descriptionRu = description ? await translateText(description, 'ru') : undefined;

      const newService = await this.prisma.$transaction(async (tx) => {
        const data: any = {
          categoryId,
          slug,
          nameUz,
        };

        if (nameEn) data.nameEn = nameEn;
        if (nameRu) data.nameRu = nameRu;
        if (descriptionEn) data.descriptionEn = descriptionEn;
        if (descriptionRu) data.descriptionRu = descriptionRu;
        if (descriptionUz) data.descriptionUz = descriptionUz;

        const service = await tx.service.create({
          data,
        });

        const categoryName = category.nameUz;

        if (seo) {
          await this.seoService.upsertSeo(SeoEntity.SERVICE, service.id, {
            ...seo,
            autoGenerated: false,
          });
        } else {
          const generatedSeo = this.seoService.generateServiceSeo({
            name: nameUz,
            slug,
            categoryName,
          });

          await this.seoService.upsertSeo(SeoEntity.SERVICE, service.id, generatedSeo);
        }

        return service;
      });

      return newService;
    } catch (error) {
      errorResponse(error);
    }
  }

  async findAll() {
    try {
      const services = await this.prisma.service.findMany();

      const serviceIds = services.map((srv) => srv.id);
      const seoRecords = await this.prisma.seo.findMany({
        where: {
          entityType: SeoEntity.SERVICE,
          entityId: { in: serviceIds },
        },
      });

      const seoMap = new Map(seoRecords.map((seo) => [seo.entityId, seo]));

      return services.map((srv) => ({
        ...srv,
        seo: seoMap.get(srv.id),
      }));
    } catch (error) {
      errorResponse(error);
    }
  }

  async findAllByCategory(categoryId: string) {
    try {
      const services = await this.prisma.service.findMany({
        where: {
          categoryId,
        },
      });

      const serviceIds = services.map((srv) => srv.id);
      const seoRecords = await this.prisma.seo.findMany({
        where: {
          entityType: SeoEntity.SERVICE,
          entityId: { in: serviceIds },
        },
      });

      const seoMap = new Map(seoRecords.map((seo) => [seo.entityId, seo]));

      return services.map((srv) => ({
        ...srv,
        seo: seoMap.get(srv.id),
      }));
    } catch (error) {
      errorResponse(error);
    }
  }

  async findOne(id: string) {
    try {
      const service = await this.prisma.service.findUnique({
        where: {
          id,
        },
      });

      if (!service) {
        throw new NotFoundException('Service not found');
      }

      const seo = await this.seoService.findSeo(SeoEntity.SERVICE, id);

      return {
        ...service,
        seo,
      };
    } catch (error) {
      errorResponse(error);
    }
  }

  async update(id: string, updateServiceDto: UpdateServiceDto) {
    try {
      const { seo, ...serviceData } = updateServiceDto;

      await this.prisma.$transaction(async (tx) => {
        await tx.service.update({
          where: {
            id,
          },
          data: serviceData,
        });

        if (seo) {
          await this.seoService.upsertSeo(SeoEntity.SERVICE, id, {
            ...seo,
            autoGenerated: false,
          });
        }
      });

      return this.findOne(id);
    } catch (error) {
      errorResponse(error);
    }
  }

  async remove(id: string) {
    try {
      await this.seoService.deleteSeo(SeoEntity.SERVICE, id);

      return await this.prisma.service.delete({
        where: { id },
      });
    } catch (error) {
      errorResponse(error);
    }
  }
}

