import { ConflictException, Injectable, NotFoundException } from '@nestjs/common';
import { CreateDistrictDto } from './dto/create-district.dto';
import { UpdateDistrictDto } from './dto/update-district.dto';
import { PrismaService } from 'src/prisma/prisma';
import { errorResponse } from 'src/utils/response';
import { translateText } from 'src/utils/translate';
import { SeoService } from 'src/seo/seo.service';
import { SeoEntity } from '@prisma/client';

@Injectable()
export class DistrictService {
  constructor(
    private readonly prisma: PrismaService,
    private readonly seoService: SeoService,
  ) {}

  async create(createDistrictDto: CreateDistrictDto) {
    try {
      const { nameUz, seo, slug, regionId } = createDistrictDto;

      const region = await this.prisma.region.findUnique({
        where: { id: regionId },
      });

      if (!region) {
        throw new NotFoundException('Region not found');
      }

      const exists = await this.prisma.district.findFirst({ where: { nameUz } });
      if (exists) {
        throw new ConflictException('District already exists');
      }

      const nameRu = nameUz ? await translateText(nameUz, 'ru') : undefined;
      const nameEn = nameUz ? await translateText(nameUz, 'en') : undefined;

      const district = await this.prisma.$transaction(async (tx) => {
        const data: any = {
          slug,
          nameUz,
          regionId,
        };

        if (nameRu) data.nameRu = nameRu;
        if (nameEn) data.nameEn = nameEn;

        const newDistrict = await tx.district.create({
          data,
        });

        if (seo) {
          await this.seoService.upsertSeo(SeoEntity.DISTRICT, newDistrict.id, {
            ...seo,
            autoGenerated: false,
          });
        } else {
          const generatedSeo = this.seoService.generateDistrictSeo({
            name: nameUz,
            slug,
            regionName: region.nameUz,
          });

          await this.seoService.upsertSeo(SeoEntity.DISTRICT, newDistrict.id, generatedSeo);
        }

        return newDistrict;
      });

      return district;
    } catch (error) {
      errorResponse(error);
    }
  }

  async findAll() {
    try {
      const districts = await this.prisma.district.findMany();

      const districtIds = districts.map((dist) => dist.id);
      const seoRecords = await this.prisma.seo.findMany({
        where: {
          entityType: SeoEntity.DISTRICT,
          entityId: { in: districtIds },
        },
      });

      const seoMap = new Map(seoRecords.map((seo) => [seo.entityId, seo]));

      return districts.map((dist) => ({
        ...dist,
        seo: seoMap.get(dist.id),
      }));
    } catch (error) {
      errorResponse(error);
    }
  }
  async findByRegion(regionId: string) {
    try {
      const districts = await this.prisma.district.findMany({
        where: { regionId },
      });

      const districtIds = districts.map((dist) => dist.id);
      const seoRecords = await this.prisma.seo.findMany({
        where: {
          entityType: SeoEntity.DISTRICT,
          entityId: { in: districtIds },
        },
      });

      const seoMap = new Map(seoRecords.map((seo) => [seo.entityId, seo]));

      return districts.map((dist) => ({
        ...dist,
        seo: seoMap.get(dist.id),
      }));
    } catch (error) {
      errorResponse(error);
    }
  }

  async findOne(id: string) {
    try {
      const district = await this.prisma.district.findUnique({
        where: { id },
        include: { region: true },
      });

      if (!district) {
        throw new NotFoundException('District not found');
      }

      const seo = await this.seoService.findSeo(SeoEntity.DISTRICT, id);

      return {
        ...district,
        seo,
      };
    } catch (error) {
      errorResponse(error);
    }
  }

  async update(id: string, updateDistrictDto: UpdateDistrictDto) {
    try {
      const { seo, ...districtData } = updateDistrictDto;

      await this.prisma.$transaction(async (tx) => {
        await tx.district.update({
          where: { id },
          data: districtData,
        });

        if (seo) {
          await this.seoService.upsertSeo(SeoEntity.DISTRICT, id, {
            ...seo,
            autoGenerated: false,
          });
        }
      });

      return this.findOne(id);
    } catch (error) {
      errorResponse(error);
    }
  }

  async remove(id: string) {
    try {
      await this.seoService.deleteSeo(SeoEntity.DISTRICT, id);

      return await this.prisma.district.delete({
        where: { id },
      });
    } catch (error) {
      errorResponse(error);
    }
  }
}
