import { ConflictException, Injectable, NotFoundException } from '@nestjs/common';
import { CreateRegionDto } from './dto/create-region.dto';
import { UpdateRegionDto } from './dto/update-region.dto';
import { PrismaService } from 'src/prisma/prisma';
import { errorResponse } from 'src/utils/response';
import { translateText } from 'src/utils/translate';
import { SeoService } from 'src/seo/seo.service';
import { SeoEntity } from '@prisma/client';

@Injectable()
export class RegionService {
  constructor(
    private readonly prisma: PrismaService,
    private readonly seoService: SeoService,
  ) {}

  async create(createRegionDto: CreateRegionDto) {
    try {
      const { nameUz, seo, slug } = createRegionDto;

      const exists = await this.prisma.region.findFirst({ where: { nameUz } });
      if (exists) {
        throw new ConflictException('Region already exists');
      }

      const nameRu = nameUz ? await translateText(nameUz, 'ru') : undefined;
      const nameEn = nameUz ? await translateText(nameUz, 'en') : undefined;

      const region = await this.prisma.$transaction(async (tx) => {
        const data: any = {
          slug,
          nameUz,
        };

        if (nameRu) data.nameRu = nameRu;
        if (nameEn) data.nameEn = nameEn;

        const newRegion = await tx.region.create({
          data,
        });

        if (seo) {
          await this.seoService.upsertSeo(SeoEntity.REGION, newRegion.id, {
            ...seo,
            autoGenerated: false,
          });
        } else {
          const generatedSeo = this.seoService.generateRegionSeo({
            name: nameUz,
            slug,
          });

          await this.seoService.upsertSeo(SeoEntity.REGION, newRegion.id, generatedSeo);
        }

        return newRegion;
      });

      return region;
    } catch (error) {
      errorResponse(error);
    }
  }

  async findAll() {
    try {
      const regions = await this.prisma.region.findMany();

      const regionIds = regions.map((reg) => reg.id);
      const seoRecords = await this.prisma.seo.findMany({
        where: {
          entityType: SeoEntity.REGION,
          entityId: { in: regionIds },
        },
      });

      const seoMap = new Map(seoRecords.map((seo) => [seo.entityId, seo]));

      return regions.map((reg) => ({
        ...reg,
        seo: seoMap.get(reg.id),
      }));
    } catch (error) {
      errorResponse(error);
    }
  }

  async findOne(id: string) {
    try {
      const region = await this.prisma.region.findUnique({
        where: { id },
        include: { districts: true },
      });

      if (!region) {
        throw new NotFoundException('Region not found');
      }

      const seo = await this.seoService.findSeo(SeoEntity.REGION, id);

      return {
        ...region,
        seo,
      };
    } catch (error) {
      errorResponse(error);
    }
  }

  async update(id: string, updateRegionDto: UpdateRegionDto) {
    try {
      const { seo, ...regionData } = updateRegionDto;

      await this.prisma.$transaction(async (tx) => {
        await tx.region.update({
          where: { id },
          data: regionData,
        });

        if (seo) {
          await this.seoService.upsertSeo(SeoEntity.REGION, id, {
            ...seo,
            autoGenerated: false,
          });
        }
      });

      return this.findOne(id);
    } catch (error) {
      errorResponse(error);
    }
  }

  async remove(id: string) {
    try {
      await this.seoService.deleteSeo(SeoEntity.REGION, id);

      return await this.prisma.region.delete({
        where: { id },
      });
    } catch (error) {
      errorResponse(error);
    }
  }
}
