import {
  IsBoolean,
  IsEnum,
  IsJSON,
  IsOptional,
  IsString,
  IsUrl,
  MaxLength,
} from 'class-validator';
import { ApiProperty, ApiPropertyOptional } from '@nestjs/swagger';
import { SeoEntity } from '@prisma/client';

export class CreateSeoDto {
  @ApiPropertyOptional({ enum: SeoEntity })
  @IsOptional()
  @IsEnum(SeoEntity)
  entityType?: SeoEntity;

  @ApiPropertyOptional({
    example: 'cmf4j7m7k0000m8w6j3v8n2p1',
  })
  @IsOptional()
  @IsString()
  entityId?: string;

  // Meta Title
  @ApiProperty({
    example: 'Qurilish kompaniyalari',
  })
  @IsString()
  @MaxLength(255)
  titleUz!: string;

  @ApiPropertyOptional()
  @IsOptional()
  @IsString()
  @MaxLength(255)
  titleRu?: string;

  @ApiPropertyOptional()
  @IsOptional()
  @IsString()
  @MaxLength(255)
  titleEn?: string;

  // Meta Description
  @ApiProperty({
    example: 'Qurilish sohasi bo\'yicha barcha tashkilotlar ro\'yxati',
  })
  @IsString()
  descriptionUz!: string;

  @ApiPropertyOptional()
  @IsOptional()
  @IsString()
  descriptionRu?: string;

  @ApiPropertyOptional()
  @IsOptional()
  @IsString()
  descriptionEn?: string;

  // Keywords
  @ApiProperty({
    example: 'qurilish,toshkent,tashkilotlar',
  })
  @IsString()
  keywordsUz!: string;

  @ApiPropertyOptional()
  @IsOptional()
  @IsString()
  keywordsRu?: string;

  @ApiPropertyOptional()
  @IsOptional()
  @IsString()
  keywordsEn?: string;

  // Canonical
  @ApiPropertyOptional({
    example: 'https://example.uz/restaurants/akfa',
  })
  @IsOptional()
  @IsUrl()
  canonical?: string;

  // Robots
  @ApiPropertyOptional({
    example: 'index,follow',
  })
  @IsOptional()
  @IsString()
  robots?: string;

  // Open Graph
  @ApiPropertyOptional()
  @IsOptional()
  @IsString()
  ogTitleUz?: string;

  @ApiPropertyOptional()
  @IsOptional()
  @IsString()
  ogTitleRu?: string;

  @ApiPropertyOptional()
  @IsOptional()
  @IsString()
  ogTitleEn?: string;

  @ApiPropertyOptional()
  @IsOptional()
  @IsString()
  ogDescriptionUz?: string;

  @ApiPropertyOptional()
  @IsOptional()
  @IsString()
  ogDescriptionRu?: string;

  @ApiPropertyOptional()
  @IsOptional()
  @IsString()
  ogDescriptionEn?: string;

  @ApiPropertyOptional()
  @IsOptional()
  @IsUrl()
  ogImage?: string;

  // Twitter
  @ApiPropertyOptional()
  @IsOptional()
  @IsString()
  twitterTitleUz?: string;

  @ApiPropertyOptional()
  @IsOptional()
  @IsString()
  twitterTitleRu?: string;

  @ApiPropertyOptional()
  @IsOptional()
  @IsString()
  twitterTitleEn?: string;

  @ApiPropertyOptional()
  @IsOptional()
  @IsString()
  twitterDescriptionUz?: string;

  @ApiPropertyOptional()
  @IsOptional()
  @IsString()
  twitterDescriptionRu?: string;

  @ApiPropertyOptional()
  @IsOptional()
  @IsString()
  twitterDescriptionEn?: string;

  @ApiPropertyOptional()
  @IsOptional()
  @IsUrl()
  twitterImage?: string;

  // JSON-LD
  @ApiPropertyOptional({
    example: '{"@context":"https://schema.org"}',
  })
  @IsOptional()
  @IsJSON()
  schema?: string;

  @ApiPropertyOptional({
    default: true,
  })
  @IsOptional()
  @IsBoolean()
  autoGenerated?: boolean;
}